// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxfflmcmemxlsthrcgye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZmZsbWNtZW14bHN0aHJjZ3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzAzODQsImV4cCI6MjA2MDY0NjM4NH0.jqQ9NOBERyqf34dc41_NEi_dKsMTyPHOpV5e-pP9eSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);